version: '3'

services:
  wordpress:
    image: wordpress:php8.0

    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

    depends_on:
      - db

    restart: 'always'
  
  db:
    image: mysql:5.7.40
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

    volumes: 
      - db-data:/var/lib/mysql

    ports:
      - 8080:80

    restart: always

volumes:
  db-data: