const myName = "Leandro";
const birthCity = "Campinas";
let birthYear = 1989;
console.log(myName);
console.log(birthCity);
console.log(birthYear);
birthYear = 2030;
console.log(birthYear);
birthCity = "São Paulo";
console.log(birthCity);