# Generated by Django 4.2.4 on 2023-08-19 02:43

from django.db import migrations, models
import playlists.validators


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "length_in_seconds",
                    models.IntegerField(
                        validators=[playlists.validators.validate_song_length]
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Music",
        ),
    ]
