# Generated by Django 4.2.4 on 2023-08-21 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0002_song_delete_music"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="singer",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="playlists.singer",
            ),
        ),
    ]
