# Generated by Django 4.2.4 on 2023-08-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0003_song_singer"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="songs",
            field=models.ManyToManyField(related_name="playlists", to="playlists.song"),
        ),
    ]
